# Generated by Django 5.1.7 on 2025-04-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_uid_teacher_teacher_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user_type',
        ),
        migrations.AddField(
            model_name='teacher',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
