# Generated by Django 5.1.7 on 2025-05-07 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_courseresource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SC', '单选题'), ('MC', '多选题'), ('FB', '填空题'), ('QA', '问答题')], max_length=2)),
                ('content', models.TextField(verbose_name='题目内容')),
                ('score', models.PositiveSmallIntegerField(default=1, verbose_name='题目分值')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='选项')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='答案')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(to='teacher.question')),
            ],
            options={
                'verbose_name': '习题任务',
                'verbose_name_plural': '习题集',
                'ordering': ['-created_at'],
            },
        ),
    ]
