# Generated by Django 5.1.7 on 2025-04-24 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_courseresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('fill', '填空题'), ('essay', '问答题')], max_length=20)),
                ('content', models.TextField(verbose_name='题目内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teacher.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assignment_type', models.CharField(choices=[('homework', '作业'), ('exam', '考试')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
            ],
        ),
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teacher.questionbase')),
                ('reference_answer', models.TextField(verbose_name='参考答案')),
                ('scoring_rubric', models.JSONField(null=True, verbose_name='评分标准')),
            ],
            bases=('teacher.questionbase',),
        ),
        migrations.CreateModel(
            name='FillInBlankQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teacher.questionbase')),
                ('correct_answer', models.TextField(verbose_name='参考答案')),
                ('keywords', models.JSONField(null=True, verbose_name='关键词')),
            ],
            bases=('teacher.questionbase',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teacher.questionbase')),
                ('options', models.JSONField(verbose_name='选项列表')),
                ('correct_answers', models.JSONField(verbose_name='正确答案集合')),
            ],
            bases=('teacher.questionbase',),
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teacher.questionbase')),
                ('options', models.JSONField(verbose_name='选项列表')),
                ('correct_answer', models.CharField(max_length=10, verbose_name='正确答案')),
            ],
            bases=('teacher.questionbase',),
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.assignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.questionbase')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='questions',
            field=models.ManyToManyField(through='teacher.AssignmentQuestion', to='teacher.questionbase'),
        ),
    ]
