# Generated by Django 5.1.7 on 2025-05-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_question_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
