# Generated by Django 5.1.7 on 2025-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_course_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='numbers',
            field=models.IntegerField(default=0),
        ),
    ]
