# Generated by Django 5.1.7 on 2025-05-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_submission_assignment_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentquestion',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='essayquestion',
            name='questionbase_ptr',
        ),
        migrations.RemoveField(
            model_name='fillinblankquestion',
            name='questionbase_ptr',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='questionbase_ptr',
        ),
        migrations.RemoveField(
            model_name='questionbase',
            name='course',
        ),
        migrations.RemoveField(
            model_name='singlechoicequestion',
            name='questionbase_ptr',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentQuestion',
        ),
        migrations.DeleteModel(
            name='EssayQuestion',
        ),
        migrations.DeleteModel(
            name='FillInBlankQuestion',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionBase',
        ),
        migrations.DeleteModel(
            name='SingleChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
