# Generated by Django 5.1.7 on 2025-05-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_question_essayquestion_fillinblankquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillinblankquestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='question',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='singlechoicequestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='EssayQuestion',
        ),
        migrations.DeleteModel(
            name='FillInBlankQuestion',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='SingleChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionBank',
        ),
    ]
