# Generated by Django 5.1.7 on 2025-04-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_alter_attendance_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='duration',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
