# Generated by Django 5.1.7 on 2025-05-08 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_questionbase_assignment_essayquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbase',
            name='course',
        ),
        migrations.AddField(
            model_name='questionbase',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
