# Generated by Django 5.1.7 on 2025-04-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_attendance_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
