# Generated by Django 5.1.7 on 2025-04-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0010_alter_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='course', to='student.student'),
        ),
    ]
