# Generated by Django 5.1.7 on 2025-05-08 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('teacher', '0010_remove_questionbase_course_questionbase_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essayquestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='fillinblankquestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='singlechoicequestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='questionbase',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
