# Generated by Django 5.1.7 on 2025-05-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_alter_essayquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essayquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fillinblankquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='singlechoicequestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='questionbase',
            name='polymorphic_ctype',
        ),
    ]
