# Generated by Django 5.1.7 on 2025-05-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_discussiontopic_discussionpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='file',
            field=models.FileField(upload_to='files/course_resources/%Y/%m/'),
        ),
    ]
