# Generated by Django 5.1.7 on 2025-05-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_alter_courseresource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportassignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='files/reports/assignments/%Y/%m/'),
        ),
    ]
