# Generated by Django 5.1.7 on 2025-05-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_face_collected'),
        ('teacher', '0016_alter_reportassignment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checked_students',
            field=models.ManyToManyField(blank=True, related_name='attendances', to='student.student'),
        ),
    ]
