# Generated by Django 5.1.7 on 2025-05-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_courseapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseApplication',
        ),
    ]
