# Generated by Django 5.1.7 on 2025-05-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_courseapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayquestion',
            name='scoring_rubric',
        ),
    ]
