# Generated by Django 5.1.7 on 2025-03-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('class_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('join_code', models.IntegerField()),
                ('class_name', models.CharField(max_length=100)),
                ('class_size', models.IntegerField(default=1)),
            ],
        ),
    ]
