# Generated by Django 5.1.7 on 2025-03-13 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_remove_experiment_class_obj_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("ClassID", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="joined_classes", to="users.user"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taught_classes",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
