# Generated by Django 5.1.7 on 2025-04-18 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=15, unique=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.college')),
            ],
        ),
    ]
