# Generated by Django 5.1.7 on 2025-04-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0002_sysadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
