# Generated by Django 5.1.7 on 2025-04-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0005_news_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_file',
            field=models.FileField(blank=True, upload_to='static/news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
