# Generated by Django 5.1.7 on 2025-05-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0007_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_file',
            field=models.FileField(blank=True, upload_to='files/news/'),
        ),
    ]
