# Generated by Django 5.1.7 on 2025-04-20 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('sys_admin', '0003_alter_college_college_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sys_admin.major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sys_admin.college'),
        ),
    ]
