# Generated by Django 5.1.7 on 2025-04-22 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_major_alter_student_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_id',
        ),
    ]
