# Generated by Django 5.1.7 on 2025-05-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_assignmentsubmission_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_collected',
            field=models.BooleanField(default=False),
        ),
    ]
