# Generated by Django 5.1.7 on 2025-05-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_face_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
