# Generated by Django 5.1.7 on 2025-05-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentanswer_score'),
        ('teacher', '0021_remove_essayquestion_scoring_rubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(upload_to='files/report_submissions/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.reportassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
